### ISSUE TITLE
If sparrest is already running, and launch 2nd instance, message is ugly

### ISSUE THREAD

**Issue by dfreniche** [kasappeal/sparrest#3]
- launch an instance of sparREST
- launch another instance
- you get a message telling you port 8000 is in use:

```
Starting a server on port 8000
Traceback (most recent call last):
  File "server.py", line 306, in <module>
    run_on(port)
  File "server.py", line 300, in run_on
    httpd = HTTPServer(server_address, SparrestHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

Can we have a more beautiful error message, without the call trace?

**Comment by kasappeal** [comment]
Sure. It will show a nice message, like when you forget send the `Content-Type: application/json` header in a POST request.

**Comment by kasappeal** [comment]
Fixed in https://github.com/kasappeal/sparrest/commit/efe907267a9f327f714e123df4ba6dc6bcbc2f8d
